steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/prj-gradient-kshama/python-repo/my-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/prj-gradient-kshama/python-repo/my-app:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-app', '--image', 'us-central1-docker.pkg.dev/prj-gradient-kshama/python-repo/my-app:latest']


